name: Playwright Automation Intent Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🌐 Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: 🚀 Run Playwright Test
        run: npm start
        env:
          API_KEY_GEMINI: ${{ secrets.API_KEY_GEMINI }}

      - name: 📅 Get current date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: 📤 Upload Test Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Automation-Report-${{ env.CURRENT_DATE }}
          # 1. Ambil semua folder tanggal hari ini di dalam subfolder report
          # 2. Tambahkan '!' untuk mengecualikan folder template secara eksplisit
          path: |
            report/**/${{ env.CURRENT_DATE }}/
            !report/template/
          retention-days: 14
